apiVersion: v1
kind: Service
metadata:
  name: {{ include "copilot-premium-usage-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.service.scrapeMetrics }}
    scrape-service-metrics: "true"
    {{- end }}
    {{- include "copilot-premium-usage-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "copilot-premium-usage-exporter.selectorLabels" . | nindent 4 }}
